image: "portus.cs.int:5000/gitlab/rust:latest"

before_script:
  ##
  ## Run ssh-agent (inside the build environment)
  ##
  - eval $(ssh-agent -s)

  ##
  ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
  ## We're using tr to fix line endings which makes ed25519 keys work
  ## without extra base64 encoding.
  ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
  ##
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null

  ##
  ## Create the SSH directory and give it the right permissions
  ##
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

  ##
  ## Move cargo home directory inside project dir
  ## so it can be cached
  ##

  - export CARGO_HOME="$(realpath ./.cargo)"
  - mkdir -p $CARGO_HOME

  ## Install build prerequisites
  - sudo add-apt-repository "deb http://aptly.cs.int/public xenial int"
  - wget http://aptly.cs.int/public/cs-repo.key -O - | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install -y libnanomsg5 libnanomsg-dev

cache:
    paths:
    - .cargo
    - target

stages:
  - test

build:
  stage: test
  tags:
  - rust
  except:
  - master
  script:
  - cargo test --all
